openapi: 3.0.0
info:
  title: Clean Architecture in Go (Testability)
  version: 1.0.0
tags:
  - name: order
    description: The orders in the service
paths:
  /testability/orders:
    post:
      summary: Create a new order
      operationId: createOrder
      tags:
        - order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        200:
          description: Create order successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedResponse'


components:
  schemas:
    CreateOrderRequest:
      type: object
      required:
        - id
        - name
        - items
      properties:
        id:
          type: string
          example: 2ef749d9-b25e-49df-8ff3-54f3873fffb8
        name:
          type: string
          example: Aotoki
        items:
          type: array
          minimum: 1
          items:
            $ref: '#/components/schemas/OrderItem'
    CreatedResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: 2ef749d9-b25e-49df-8ff3-54f3873fffb8
    OrderItem:
      type: object
      required:
        - name
        - quantity
        - unit_price
      properties:
        name:
          type: string
          example: Apple
        quantity:
          type: number
          minimum: 1
          example: 1
        unit_price:
          type: number
          minimum: 1
          example: 10
