// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/elct9620/clean-architecture-in-go-2025/internal/api/grpc"
	"github.com/elct9620/clean-architecture-in-go-2025/internal/repository"
	"github.com/elct9620/clean-architecture-in-go-2025/internal/usecase"
	"github.com/elct9620/clean-architecture-in-go-2025/internal/validator"
)

// Injectors from wire.go:

func initialize() (*grpc.Server, error) {
	inMemoryOrderRepository := repository.NewInMemoryOrderRepository()
	inMemoryTokenRepository, err := repository.NewInMemoryTokenRepository()
	if err != nil {
		return nil, err
	}
	validatorValidator := validator.New()
	placeOrder := usecase.NewPlaceOrder(inMemoryOrderRepository, inMemoryTokenRepository, validatorValidator)
	lookupOrder := usecase.NewLookupOrder(inMemoryOrderRepository, inMemoryTokenRepository)
	orderServer := &grpc.OrderServer{
		PlaceOrderUsecase:  placeOrder,
		LookupOrderUsecase: lookupOrder,
	}
	server := grpc.NewServer(orderServer)
	return server, nil
}
