// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/elct9620/clean-architecture-in-go-2025/internal/api/grpc"
)

// Injectors from wire.go:

func initialize() (*grpc.Server, error) {
	orderServer := grpc.NewOrderServer()
	server := grpc.NewServer(orderServer)
	return server, nil
}
